GCC5-GCC6 Compiler Error Fixes gcc5: gpu: msm: fix 5.0 compile
* These need to be static to avoid these errors:

drivers/built-in.o: In function `.LANCHOR1':
msm_iommu_sec.c:(.data+0x9298): undefined reference to `kgsl_iommu_sync_lock'
msm_iommu_sec.c:(.data+0x929c): undefined reference to `kgsl_iommu_sync_unlock'
Makefile:877: recipe for target '.tmp_vmlinux1' failed
make: *** [.tmp_vmlinux1] Error 1

Signed-off-by: Chet Kener <Cl3Kener@gmail.com>

gcc5: fix warnings spam with gcc5

This fixes 102 warnings

Signed-off-by: Paul Beeler <pbeeler80@gmail.com>

gcc5: makefile: if -O3 disable array-bounds false positive

gcc5: sound/soc/codecs/wcd9xxx-mbhc.c fix warning: initialization discards 'const' qualifier from pointer target type

gcc5: arm: enable cortex_a15 optimization

gcc5: drivers/staging/prima/CORE/MAC/src/pe/sch/schBeaconGen.c: fix warning: passing argument 2 of 'vos_mem_compare' discards 'const' qualifier from pointer target type

gcc5: drivers/staging/prima/CORE/HDD/src/wlan_hdd_wmm.c: fix warning: logical not is only applied to the left hand side of comparison

gcc5: drivers/video/msm/mdss/mdss_mdp_pp.c: fix warning: logical not is only applied to the left hand side of comparison

gcc5: drivers/video/msm/mdss/mdss_mdp_pp.c: fix warning: comparison of constant '15' with boolean expression is always false

Conflicts:
	Makefile